create table if not exists public.september_survey_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  role text not null check (role in ('student', 'teacher')),
  respondent_name text not null,
  grade text,
  availability jsonb not null,
  memo text,
  unique (role, respondent_name)
);

alter table public.september_survey_submissions enable row level security;

drop policy if exists "allow survey insert" on public.september_survey_submissions;
drop policy if exists "allow survey select" on public.september_survey_submissions;
drop policy if exists "allow survey update" on public.september_survey_submissions;
drop policy if exists "allow survey delete" on public.september_survey_submissions;

revoke select, insert, update, delete, truncate, references, trigger, maintain
on table public.september_survey_submissions
from anon;

create table if not exists public.september_survey_people (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  role text not null check (role in ('student', 'teacher')),
  name text not null,
  grade text,
  active boolean not null default true,
  unique (role, name)
);

alter table public.september_survey_people enable row level security;

drop policy if exists "allow people select" on public.september_survey_people;
drop policy if exists "allow people insert" on public.september_survey_people;
drop policy if exists "allow people update" on public.september_survey_people;

revoke select, insert, update, delete, truncate, references, trigger, maintain
on table public.september_survey_people
from anon;

-- Apply create-token-access.sql before deploying the token-based form.
